server:
  port: 9393

spring:
  main:
    banner-mode: off
  application:
    name: code-eval-engine
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms_code_eval_engine #${DB_HOST_PORT}
    username: postgres #${DB_POSTGRE_USER}
    password: postgres #${DB_POSTGRE_PASS}
    hikari:
      poolName: MsCodeEvalEngineHikariPool
      auto-commit: false
      maximum-pool-size: 4 #${HIKARICP_DEFAULT_POOL_SIZE}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
    show-sql: true #will be false on prod
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
